export const PRODUCTS_BASEURL = 'https://rabbitmart-cms.vercel.app/products'
export const ORDERS_BASEURL = 'https://rabbitmart-cms.vercel.app/orders'
export const SHIPPING_BASEURL = 'https://rabbitmart-cms.vercel.app/shipping'
export const USER_BASEURL = 'https://rabbitmart-cms.vercel.app/me'
export const PAYMENTS_BASEURL = 'https://rabbitmart-cms.vercel.app/payments'