export const WEBSITE_BASE_URL = 'https://rabbitmart-cm.vercel.app'
export const PRODUCTS_BASEURL = 'https://rabbitmart-cms.vercel.app/products'
export const ORDERS_BASEURL = 'https://rabbitmart-cms.vercel.app/orders'
export const SHIPPING_BASEURL = 'https://rabbitmart-cms.vercel.app/shipping'
export const NOTIFICATIONS_BASEURL = 'https://rabbitmart-cms.vercel.app/notifications'
export const PAYMENT_BASEURL = 'https://rabbitmart-cms.vercel.app/payment'
export const USER_BASEURL = 'https://rabbitmart-cms.vercel.app/me'