export const FETCH_RECOMMENDATIONS = 'FETCH_RECOMMENDATIONS';
export const VALIDATE_CART = 'PRODUCTS_VALIDATE_CART';
export const UPDATE_DATABASE = 'PRODUCTS_UPDATE_DATABASE';


export const VALIDATE_CART_ERR = 'PRODUCTS_VALIDATE_CART_ERR';